namespace Shared.Domain.Enums;

public enum MovementEventType
{
    TransactionCreated = 1,
    TransactionApproved = 2,
    PayoutCreated = 3,
    PayoutFinished = 4,
    PayoutFinishedRefund = 5,
    PayoutError = 6,
    ClaimOpen = 7,
    ClaimClose = 8,
    ClaimCloseModified = 9,
    ClaimRefund = 10,
    ClaimReopen = 11,
    ChargebackReopen = 12,
    ChargebackOpen = 13,
    ChargebackClose = 14,
    ChargebackCloseModified = 15,
    ChargebackRefund = 16,
    SettlementPublished = 17,
    SettlementUnpublished = 18,
    PaymentOrderPaid = 19,
    PaymentOrderProcessed = 20,
    PaymentOrderProcess = 21,
    PaymentOrderPaidReversed = 22,
    PaymentOrderCancelled = 23,
    WithdrawalApproved = 24,
    WithdrawalCancelled = 25,
    WithdrawalPaid = 26,
    WithdrawalReturned = 27,
    AdjustmentCreated = 28,
    AdjustmentTopupCreated = 29,
    TopupCreated = 30,
    AdjustmentRollingReserveCreated = 31,
    AdjustmentBalanceFeeCreated = 32,
    AdjustmentRebateFeeCreated = 33,
    RollingReserveReleased = 34,
    AccountSettlement = 35,
    PartialPayment = 36
}
